---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--enable-plugin=aws
          - --args=--disable-rule=aws_route53_record_invalid_health_check_id
          - --args=--disable-rule=aws_route53_record_invalid_name
          - --args=--disable-rule=aws_route53_record_invalid_set_identifier
          - --args=--disable-rule=aws_route53_record_invalid_type
          - --args=--disable-rule=aws_route53_record_invalid_zone_id
      - id: terraform_providers_lock
