version: 2.1

orbs:
  terraform: "circleci/terraform@3.1.0"

executors:
  default:
    working_directory: "/tmp/terraform"
    resource_class: small
    docker:
      - image: hashicorp/terraform:1.2.3

jobs:
  comment_on_pr:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Comment on PR
          command: |
            terraform init
            apk add jq jo curl

            pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
            -u $GITHUB_USER:$GITHUB_TOKEN)

            if [ $(echo $pr_response | jq length) -eq 0 ]; then
              echo "No PR found to update"
              exit 0
            else
              comment=$(jo body="\`\`\`\n$(terraform show -no-color tfplan)")
              pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
              curl --location --request POST "$pr_comment_url" \
              -u $GITHUB_USER:$GITHUB_TOKEN \
              --header 'Content-Type: application/json' \
              --data-raw "$comment"
            fi

  fmt_validate_terraform:
    executor: default
    steps:
      - checkout
      - terraform/init
      - terraform/fmt
      - terraform/validate

  plan_terraform:
    executor: default
    steps:
      - checkout
      - terraform/init
      - terraform/plan:
          out: tfplan
      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  apply_terraform:
    executor: default
    steps:
      - checkout
      - terraform/init
      - terraform/apply

workflows:
  version: 2
  terraform:
    jobs:
      - fmt_validate_terraform:
          context: trade-tariff
      - plan_terraform:
          context: trade-tariff
          requires:
            - fmt_validate_terraform
      - comment_on_pr:
          context: trade-tariff
          requires:
            - plan_terraform
      - hold_apply_terraform:
          type: approval
          requires:
            - comment_on_pr
          filters:
            branches:
              only:
                - main
      - apply_terraform:
          context: trade-tariff
          requires:
            - hold_apply_terraform
          filters:
            branches:
              only:
                - main
